services:
  middle_layer:
    build:
      context: .
      dockerfile: Dockerfile.middle
    container_name: middle_layer
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./chat_pdf:/app
      - pdf_storage:/app/uploads  # Volume for PDF storage
      - vector_storage:/app/vector_db  # Volume for RAG vector data
      - chroma_db:/app/chroma_db  # Volume for Chroma vector database
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: streamlit_app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - middle_layer
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

  user_chat:
    build:
      context: .
      dockerfile: Dockerfile.user_chat
    container_name: user_chat
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    depends_on:
      - middle_layer
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

volumes:
  pdf_storage:  # Named volume for PDF storage
  vector_storage:  # Named volume for RAG vector data
  chroma_db: # Named volume for Chroma vector database
