version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 8G

  streamlit-app:
    build: .
    container_name: streamlit_app
    volumes:
      - .:/app
    ports:
      - 8501:8501
    depends_on:
      - ollama
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G
